title = "Anurag Kar"
baseURL = "https://anuragkar.netlify.app/"
languageName = "English"
languageCode = "en-us"
relativeURLs = true

[params]
  author = "Anurag Kar"
  description = "Devon's Portfolio"

dsiableKinds = [ "page", "section", "taxonomy", "term" ]

[[menus.sections]]
name = "About"
weight = 1

[[menus.sections]]
name = "Projects"
weight = 2

[[menus.sections]]
name = "Blogs"
weight = 3

[outputs]
home = [ "HTML", "About", "Blog", "Project" ]

[outputFormats.About]
path = "about"
mediaType = "text/html"
isHTML = true
permalinkable = true
notAlternative = true

[outputFormats.Blog]
path = "blogs"
mediaType = "text/html"
isHTML = true
permalinkable = true
notAlternative = true

[outputFormats.Project]
path = "projects"
mediaType = "text/html"
isHTML = true
permalinkable = true
notAlternative = true

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[social]
email = "mailto:anuragkar16@gmail.com"
twitter = "https://twitter.com/AnuragKar016"
linkedin = "https://www.linkedin.com/in/anurag-kar-472587192/"
youtube = "https://www.youtube.com/channel/UCrWytD5s1b29limBpsis9RQ"
github = "https://github.com/anuragdevon"


[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/bootstrap.bundle.min.js"
