title: devon
baseURL: https://anuragkar16.netlify.app/
languageCode: en-us
relativeURLs: true
Author: Anurag kar

outputs:
  home:
    - HTML
    - About
    - Blog
    - Project
    - Contact

outputFormats:
  About:
    path: about
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true

  Blog:
    path: blog
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true

  Project:
    path: project
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true

  Contact:
    path: contact
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true
  
dsiableKinds:
  - page
  - section
  - taxonomy
  - term

module:
  mounts:
    - source: static
      target: static
    - source: ../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js
