title = "Anurag Kar"
baseURL = "https://anuragkar.netlify.app/"
relativeURLs = true
disableKinds = ["page", "section", "taxonomy", "term"]

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

[params]
Author = "Anurag Kar"
Description = "Personal Website"
github = "https://github.com/anuragdevon"
facebook = "https://www.facebook.com/anurag.kar.395"
sitename = "Anurag Kar website"
twitter = "https://twitter.com/AnuragKar016"


[[menus.sections]]
name = "About"
weight = 1

[[menus.sections]]
name = "Projects"
weight = 2

[[menus.sections]]
name = "Blogs"
weight = 3

[outputs]
home = [ "HTML", "About", "Blog", "Project" ]

[outputFormats.About]
path = "about"
mediaType = "text/html"
isHTML = true
permalinkable = true
notAlternative = true

[outputFormats.Blog]
path = "blogs"
mediaType = "text/html"
isHTML = true
permalinkable = true
notAlternative = true

[outputFormats.Project]
path = "projects"
mediaType = "text/html"
isHTML = true
permalinkable = true
notAlternative = true




# [[module.mounts]]
# source = "static"
# target = "static"

[[module.mounts]]
source = "../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/bootstrap.bundle.min.js"
